<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0NNQGPI" failures="1" tests="2" name="Login and Update Profile Test" time="70.482" errors="0" timestamp="2020-09-09T05:23:07 TRT">
  <testcase classname="AutomationTest.BrightTalkTest.RunnerTest" name="feature" time="58.446">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: did not expect to find [false] but found [true]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: did not expect to find [false] but found [true]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at AutomationTest.BrightTalkTest.RunnerTest.feature(RunnerTest.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.AssertionError: did not expect to find [false] but found [true]
at AutomationTest.BrightTalkTest.StepDefinition.verifyDelayedResponse(StepDefinition.java:221)
at âœ½.Then I should see that every user has a unique id(src/test/java/API-Test.feature:40)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase classname="AutomationTest.BrightTalkTest.RunnerTest" name="feature" time="11.473"/>
</testsuite> <!-- Login and Update Profile Test -->
